server:
  port: 8084
spring:
  kafka:
    producer:
      bootstrap-servers: 192.168.56.111:9092,192.168.56.112:9092,192.168.56.113:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.ByteArraySerializer