server:
  port: 8084
spring:
  kafka:
    producer:
      bootstrap-servers: localhost:9191,localhost:9192,localhost:9193
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.ByteArraySerializer

encoding:
  topic: 'encoding-tasks'