server:
  port: 8085
spring:
  kafka:
    consumer:
      bootstrap-servers: 192.168.56.111:9092,192.168.56.112:9092,192.168.56.113:9092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
      group-id: encoding-services
      enable-auto-commit: false
      max-poll-records: 1
    listener:
      ack-mode: manual_immediate
    producer:
      bootstrap-servers: 192.168.56.111:9092,192.168.56.112:9092,192.168.56.113:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.ByteArraySerializer